services:
  backup-db:
    build: .
    container_name: sql-backup
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - backup-network

networks:
  backup-network:
    driver: bridge
